CREATE TABLE webhooks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    webhook_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_webhooks PRIMARY KEY (id)
);